### ISSUE TITLE
Status of proposal

### ISSUE THREAD

**Issue by PhilippeLeLong** [sierkov/voting-agents#2]
Hi Alex, 

I'd like to know if this proposal has already been fully implemented? Is there a way to get in contact with you? Do you have a Twitter account?

**Comment by sierkov** [comment]
Hi, thanks for reaching out. It's a POC (the proposal was for a POC), and it can be tested with real users in a low-risk setting with quick iterations, such as Rapid Funding with small weekly allocations. There is a specific vision of how to do that and it's to be shared as a Fund 10 proposal. User feedback and real behavioral data are the requirements for a next major improvement.

Of course, since this is a POC, there are technical caveats, but those are use-case dependent. So, if you have a specific use case in mind, please, let me know.

Regarding how best to get in contact, it's via Ideascale (comments on the proposal or send a direct message) or via a github issue. I prefer deeper and facts-driven discussions, and, in my opinion, Twitter isn't the best format for that.

P.S. I'm closing this issue, since it's neither a description of a specific problem nor a request for improvement.
